version: '2'

networks:
  app-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper-server
    networks:
      - app-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    hostname: kafka-server
    networks:
      - app-net
    ports:
      - '9093:9093'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka-server:9092,EXTERNAL://localhost:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  redis:
    image: 'bitnami/redis:latest'
    hostname: redis
    networks:
      - app-net
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  grafana:
    image: 'bitnami/grafana:latest'
    hostname: grafana
    networks:
      - app-net
    ports:
      - '3000:3000'
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
  producer:
    build: ./producer
    image: 'user-counter/producer'
    networks:
      - app-net
    depends_on:
      - zookeeper-server
      - kafka-server
