version: '2'

networks:
  app-net:
    driver: bridge

services:
  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    networks:
      - app-net
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka-server:
    image: 'bitnami/kafka:latest'
    networks:
      - app-net
    ports:
      - '9092:9092'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper-server
  redis:
    image: 'bitnami/redis:latest'
    ports:
      - '6379:6379'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-net
  grafana:
    image: 'bitnami/grafana:latest'
    ports:
      - '3000:3000'
    networks:
      - app-net
    environment:
      - GF_INSTALL_PLUGINS=redis-datasource
  producer:
    build: ./producer
    image: 'user-counter/producer'
    depends_on:
      - zookeeper-server
      - kafka-server
